### ISSUE TITLE
Excluding Jovani 60 breaks Jovani's tab

### ISSUE THREAD

**Issue by SadieDragon** [SadieDragon/TPR-Hints-Tool#70]
Thank you to Ninjano for pointing this out.

I had decided to release without checking the stronger hints than Strong and Balanced because the worst that should happen is extra garbage.
Uhm. No. Jovani's tab straight up disappears.

Agitha's tab is also giving great sadness for every seed.

**Comment by SadieDragon** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\jpfos\AppData\Local\Programs\Python\Python313-32\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "C:\Users\jpfos\Downloads\TPR-Hints-Tool-beta\TPR-Hints-Tool-beta\hints\gui\PickSpoiler.py", line 43, in <lambda>
    c = lambda: dump_and_autofill(spoiler_log,
                ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
                                  notebook,
                                  ^^^^^^^^^
                                  pop_up,
                                  ^^^^^^^
                                  root)
                                  ^^^^^
  File "C:\Users\jpfos\Downloads\TPR-Hints-Tool-beta\TPR-Hints-Tool-beta\hints\data\parse\SpoilerLog.py", line 33, in dump_and_autofill
    parse_hints(data, notebook)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\jpfos\Downloads\TPR-Hints-Tool-beta\TPR-Hints-Tool-beta\hints\data\parse\Hints.py", line 38, in parse_hints
    JovaniTab(notebook, hint_text)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jpfos\Downloads\TPR-Hints-Tool-beta\TPR-Hints-Tool-beta\hints\gui\shopping\Jovani.py", line 20, in __init__
    self.auto_fill(sign_text)
    ~~~~~~~~~~~~~~^^^^^^^^^^^
  File "C:\Users\jpfos\Downloads\TPR-Hints-Tool-beta\TPR-Hints-Tool-beta\hints\gui\shopping\Jovani.py", line 28, in auto_fill
    rewards = self.findall_to_list(r'^(.*\)) +(\d+ .*)$', sign_text)
  File "C:\Users\jpfos\Downloads\TPR-Hints-Tool-beta\TPR-Hints-Tool-beta\hints\gui\shopping\Jovani.py", line 62, in findall_to_list
    return [*findall(regex, to_parse)[0]]
             ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by SadieDragon** [comment]
excluding 60 checks seems to be causing the above error, more specifically, so i'm updating this
